#!/bin/bash

# Bootstrap script for Terraform backend infrastructure
# This script creates the storage account needed for remote state before Terraform can manage it

set -e

# Configuration
LOCATION="West Europe"
RESOURCE_GROUP_PREFIX="terraform-backend"
STORAGE_ACCOUNT_PREFIX="tfstate"
CONTAINER_NAME="tfstate"
SUBSCRIPTION_ID=""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if Azure CLI is installed and logged in
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    if ! command -v az &> /dev/null; then
        log_error "Azure CLI is not installed. Please install it first."
        exit 1
    fi
    
    if ! az account show &> /dev/null; then
        log_error "Not logged in to Azure. Please run 'az login' first."
        exit 1
    fi
    
    SUBSCRIPTION_ID=$(az account show --query id -o tsv)
    log_success "Azure CLI is installed and logged in to subscription: $SUBSCRIPTION_ID"
}

# Generate unique suffix
generate_suffix() {
    SUFFIX=$(openssl rand -hex 4)
    RESOURCE_GROUP_NAME="${RESOURCE_GROUP_PREFIX}-${SUFFIX}"
    STORAGE_ACCOUNT_NAME="${STORAGE_ACCOUNT_PREFIX}${SUFFIX}"
    
    log_info "Generated unique suffix: $SUFFIX"
    log_info "Resource Group: $RESOURCE_GROUP_NAME"
    log_info "Storage Account: $STORAGE_ACCOUNT_NAME"
}

# Create resource group
create_resource_group() {
    log_info "Creating resource group: $RESOURCE_GROUP_NAME"
    
    az group create \
        --name "$RESOURCE_GROUP_NAME" \
        --location "$LOCATION" \
        --tags "purpose=terraform-backend" "environment=workshop" \
        --output table
    
    log_success "Resource group created successfully"
}

# Create storage account
create_storage_account() {
    log_info "Creating storage account: $STORAGE_ACCOUNT_NAME"
    
    az storage account create \
        --name "$STORAGE_ACCOUNT_NAME" \
        --resource-group "$RESOURCE_GROUP_NAME" \
        --location "$LOCATION" \
        --sku "Standard_LRS" \
        --kind "StorageV2" \
        --access-tier "Hot" \
        --allow-blob-public-access false \
        --tags "purpose=terraform-backend" "environment=workshop" \
        --output table
    
    log_success "Storage account created successfully"
}

# Enable versioning
enable_versioning() {
    log_info "Enabling blob versioning on storage account"
    
    az storage account blob-service-properties update \
        --account-name "$STORAGE_ACCOUNT_NAME" \
        --resource-group "$RESOURCE_GROUP_NAME" \
        --enable-versioning true \
        --output table
    
    log_success "Blob versioning enabled"
}

# Create container
create_container() {
    log_info "Creating storage container: $CONTAINER_NAME"
    
    az storage container create \
        --name "$CONTAINER_NAME" \
        --account-name "$STORAGE_ACCOUNT_NAME" \
        --auth-mode login \
        --output table
    
    log_success "Storage container created successfully"
}

# Generate backend configuration
generate_backend_config() {
    local config_file="backend-config.tf"
    
    log_info "Generating backend configuration file: $config_file"
    
    cat > "$config_file" << EOF
# Backend configuration for Terraform state
# This file was generated by the bootstrap script

terraform {
  backend "azurerm" {
    resource_group_name  = "$RESOURCE_GROUP_NAME"
    storage_account_name = "$STORAGE_ACCOUNT_NAME"
    container_name       = "$CONTAINER_NAME"
    key                  = "terraform.tfstate"
  }
}
EOF
    
    log_success "Backend configuration saved to $config_file"
}

# Generate variables file for the main module
generate_variables_file() {
    local vars_file="terraform.tfvars"
    
    log_info "Generating variables file: $vars_file"
    
    cat > "$vars_file" << EOF
# Variables for the backend module
# This file was generated by the bootstrap script

resource_group_name      = "$RESOURCE_GROUP_NAME"
storage_account_prefix   = "$STORAGE_ACCOUNT_PREFIX"
container_name          = "$CONTAINER_NAME"
location                = "$LOCATION"

tags = {
  purpose     = "terraform-backend"
  environment = "workshop"
  managed_by  = "terraform"
}
EOF
    
    log_success "Variables file saved to $vars_file"
}

# Generate migration instructions
generate_migration_instructions() {
    local instructions_file="migration-instructions.md"
    
    log_info "Generating migration instructions: $instructions_file"
    
    cat > "$instructions_file" << EOF
# Backend Migration Instructions

The bootstrap process has created the following resources:
- Resource Group: \`$RESOURCE_GROUP_NAME\`
- Storage Account: \`$STORAGE_ACCOUNT_NAME\`
- Container: \`$CONTAINER_NAME\`

## Next Steps

1. **Import the existing resources into Terraform state:**
   \`\`\`bash
   # Initialize Terraform with local state first
   terraform init
   
   # Import the resource group
   terraform import azurerm_resource_group.backend /subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP_NAME
   
   # Import the storage account
   terraform import azurerm_storage_account.backend /subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP_NAME/providers/Microsoft.Storage/storageAccounts/$STORAGE_ACCOUNT_NAME
   
   # Import the container
   terraform import azurerm_storage_container.tfstate https://$STORAGE_ACCOUNT_NAME.blob.core.windows.net/$CONTAINER_NAME
   \`\`\`

2. **Verify the import was successful:**
   \`\`\`bash
   terraform plan
   \`\`\`
   This should show no changes needed.

3. **Configure remote backend (copy the generated backend-config.tf to your main.tf):**
   \`\`\`bash
   # Copy the backend configuration to main.tf or create a separate backend.tf file
   cat backend-config.tf >> main.tf
   
   # Reinitialize with the backend
   terraform init -migrate-state
   \`\`\`

4. **Verify remote state is working:**
   \`\`\`bash
   terraform plan
   \`\`\`

The backend is now fully managed by Terraform and the state is stored remotely!
EOF
    
    log_success "Migration instructions saved to $instructions_file"
}

# Main execution
main() {
    log_info "Starting Terraform backend bootstrap process..."
    
    check_prerequisites
    generate_suffix
    create_resource_group
    create_storage_account
    enable_versioning
    create_container
    generate_backend_config
    generate_variables_file
    generate_migration_instructions
    
    log_success "Bootstrap process completed successfully!"
    echo
    log_warning "IMPORTANT: Please follow the instructions in migration-instructions.md to complete the setup."
    echo
    log_info "Summary of created resources:"
    echo "  Resource Group:  $RESOURCE_GROUP_NAME"
    echo "  Storage Account: $STORAGE_ACCOUNT_NAME"  
    echo "  Container:       $CONTAINER_NAME"
    echo "  Location:        $LOCATION"
}

# Run main function
main "$@"